export const GET_USERS = "GET/USERS"
export const GET_POSTS = "GET/POSTS"
export const GET_USER_POSTS = "GET/USER/POSTS"
export const GET_SINGLE_POST = "GET/SINGLE/POST"
export const GET_MESSAGES = "GET/MESSAGES"
